### ISSUE TITLE
[FEATURE REQUEST] Make API public

### ISSUE THREAD

**Issue by chhoumann** [chhoumann/quickadd#138]
### Discussed in https://github.com/chhoumann/quickadd/discussions/135

<div type='discussions-op-text'>

<sup>Originally posted by **ramon86** November  3, 2021</sup>
I hope this is something that's easy to achieve, but I cannot figure out how to use QuickAddAPI in other javascript contexts (in my case within a dataviewjs block).

The examples all work with it being available from the params object that's passed when you use actual QuickAdd macros, but is it possible to reference it on other ways as well?</div>

**Comment by tbastos** [comment]
Hi @chhoumann, thanks so much for your plugins!

Do you know any workaround to invoke QuickAdd choices from other plugins (e.g. from Templater user scripts)? My setup relies on QuickAdd macros for many things, and now I'm blocked by the inability to invoke these from other scripts.

Use case: when I create notes via QuickAdd, it automatically adds references to the new note in several places. However, I can't prevent notes from also being created outside QuickAdd (for example, by following an internal link to a non-existing note). In such cases, I can only trigger the necessary automation via the file's template (via a Templater user script). But since my automation is purely QuickAdd macros, and these can't be invoked from a Templater script, my hands are tied.

Thanks for your help!

**Comment by MicheleDeZen** [comment]
Hi,
Awesome plugin!
Is there any news regarding the api being "public"? thanks
