### ISSUE TITLE
[BUG] DATE return incorrect result

### ISSUE THREAD

**Issue by Seraphli** [chhoumann/quickadd#175]
**Describe the bug**
{{DATE:YYYY-MM-DD HH:MM:SS Z}} retruns incorrect result.

**To Reproduce**
1. Set the format to {{DATE:YYYY-MM-DD HH:MM:SS Z}}

**Expected behavior**
correct datetime 

**Screenshots**
![image](https://user-images.githubusercontent.com/1586755/150384768-ddb25da1-377f-4be7-a4b8-e43f381f7eb0.png)
![image](https://user-images.githubusercontent.com/1586755/150385143-33579fb5-7f48-490e-ad8c-96059ed8fff5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.4.18

**Comment by bathrobe** [comment]
same problem! week is off by one

**Comment by chhoumann** [comment]
Hi @Seraphli 

Thank you for reporting this.

From your query, `{{DATE:YYYY-MM-DD HH:MM:SS Z}}`, I assume you wanted the date formatted as:
Year-Month-Day Hour-Minute-Seconds Timezone.

However, you specified it in:
Year-Month-Day Hour-Month-FractionalSecond Timezone

Which leads to the incorrect date. Please see https://momentjs.com/docs/#/displaying/format/ for reference.

@bathrobe if you are having a similar issue, would you check that this is not due to something similar to the above?
If it is not, I would encourage you to open an issue with further details.
