### ISSUE TITLE
[BUG] Template variables not processed?

### ISSUE THREAD

**Issue by nousernameavailableanymore** [chhoumann/quickadd#276]
Maybe I m doing something wrong here (new to the plugin).
I created a "Template" Quick add and selected the template from the list (using the Obsidian core plugin, NOT templater).
However, template variables like `{{title}}` are not being processed.
When I run the Obisidian command to add the template to the current note, it works fine

**To Reproduce**
1. Create a template (with core plugin) using variable `{{title}}` somewhere in the template
2. Create Quick Add Choice of type "Template"
3. Select the template created in 1.
4. Run the Quick Add command

**Expected behavior**
New note gets created using the specified template. `{{title}}` variable gets replaced with actual value.

**Actual behavior**
New note gets created, however `{{title}}` does not get replaced.

**Comment by stephenalandavis** [comment]
Just wanted to add that this also doesn't work with the other template variables: `{{date}}` `{{time}}`.

**Comment by Helaxious** [comment]
This is happening to me too.

**Comment by GinoReiji** [comment]
I have this problem, too. {{title}} stays as {{title}}

**Comment by mpietrusa** [comment]
Confirm, it does not work for me too. I installed latest version.

**Comment by Amparose** [comment]
> Just wanted to add that this also doesn't work with the other template variables: `{{date}}` `{{time}}`.

I got it working with `{{DATE:YYYY/MM/DD}} at {{DATE:HH:mm}}`. Looks like this uses a different style: [Format syntax | QuickAdd](https://quickadd.obsidian.guide/docs/FormatSyntax); bit annoying that this plugin doesn't at least convert for the built-in variable defaults.

**Comment by chhoumann** [comment]
Hi everyone, thank you for contributing to the discussion here!

This isn't a bug. It is intended.
I can see, however, that this is something which could contribute to the experience of using QA.

There are two reasons why I haven't implemented this already:
1. Obsidian is closed-source, so it isn't as simple as just invoking the core plugin (as it is with Templater) and having it do it.
2. The `title` is an issue. The reason it works with `<% tp.file.title %>` (Templater) is because that is done after creating the note. QuickAdd tries to do things before actually creating the note.

As a compromise, I have allowed all format syntax to be lowercase as of #326, or v0.7.0. Meaning, `{{DATE}}` is now equivalent to `{{date}}`.

That leaves `{{time}}` and `{{title}}`.
As @Amparose mentions, you can use `{{DATE:YYYY/MM/DD}}` and `{{DATE:HH:mm}}` (or lowercase now) for `{{date}}` and `{{time}}`, respectively. This was the indented use from the start.

I may implement `{{title}}` at some later date. Please track #327 for this.

Again, thank you everyone for contributing! It is very much appreciated.

**Comment by gammaflip** [comment]
I'm currently experiencing this issue, even with e.g. {{date}}

Is there a more recent open issue?
