### ISSUE TITLE
Quickadd Capture to Daily Note location not working

### ISSUE THREAD

**Issue by chanraerae** [chhoumann/quickadd#296]
**Describe the bug**
Hi Christian,

I would like to ask please if you can kindly assist me. 

I'm trying to get quick add to capture my log into my daily note.
My daily note files are located in my Dashboard. **'1. Dashboards/Reset/1. Daily/{{YYYY-MM-DD}}.md'**
I have daily notes templates stored in 0. Templates/Daily Template.md
I don't always have daily notes active, so I have this capture set to create file if it doesn't exist yet,
and to create the daily note to the same location as above, 1. Dashboards/Reset/1. Daily{{YYYY-MM-DD}}.md

I have Insert After enabled.
The goal was to get quick add inserted after heading ### Log 
(formatted as ### <mark style="background: #ABF7F7A6;">Log</mark>) - Does formatting matter? or ### Log would suffice?

and I also have the Capture format, everything else is disabled. (Capture to active file, Task, Write to bottom of file, Append link, Insert at end of section, Create line if not found, Open)

My hot key is CTRL + . (full stop), I'm anywhere my vault, I think of something, I hotkey and quick capture log to my daily, and instead of it appending a value after ### Log

it creates a new note at my root.

**To Reproduce**

<img width="469" alt="image" src="https://user-images.githubusercontent.com/107793108/197325619-5686cfa8-197d-4457-8caf-5befbc14f017.png">
<img width="466" alt="image" src="https://user-images.githubusercontent.com/107793108/197325638-5b7f5df8-892f-4786-960b-a3ade924b0bd.png">

This is what happens, it creates a new file in the root instead.

<img width="447" alt="image" src="https://user-images.githubusercontent.com/107793108/197325743-0ae562c9-33f2-48b7-8eac-e03eb2482015.png">

and inserts the log capture, as expected, after the ### Log heading
<img width="431" alt="image" src="https://user-images.githubusercontent.com/107793108/197325811-7b8349f9-56de-4c94-aab2-5a5c95e35592.png">

**Expected behavior**
This is the expected behavior
<img width="234" alt="image" src="https://user-images.githubusercontent.com/107793108/197325707-87e80f11-61ce-4745-8ff4-c571523a9a4b.png">

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 11, 21H2 build 22000.1098 
 - Browser [e.g. chrome, safari] chrome safari and edge
 - Version [e.g. 22] obsidian 1.0.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by a-wendler** [comment]
Looks like the format of the filename ist wrong.

I think It should be `1. Dashboards/Reset/1. Daily/{{DATE:YYYY-MM-DD}}.md`

**Comment by chhoumann** [comment]
Hi @chanraerae,

First: @a-wendler is correct. The format syntax needs to have `DATE` in it, otherwise it doesn't register.
Correct: `1. Dashboards/Reset/1. Daily/{{DATE:YYYY-MM-DD}}.md`

This can be verified by looking at the file name here:
![image](https://user-images.githubusercontent.com/29108628/197820421-f72819c0-25e8-4dc6-beec-03ed74e3668c.png)
You'll see that it shows the correct entry for todays date.

I checked the other syntax in your setup, and that looks correct.

The format does matter for insertion, as it looks for matches in the file.

Here is the format syntax documentation for reference:
[https://github.com/chhoumann/quickadd/blob/master/docs/FormatSyntax.md](https://github.com/chhoumann/quickadd/blob/master/docs/FormatSyntax.md)

Thank you for providing so many details, it really helps diagnose!

Please do update me on whether this helped.

**Comment by chanraerae** [comment]
woaw, it works now. like magic. how can i have not seen that, classic, doesn't really help if I've been up for 15 hours... thanks chhoumann and a-wendler.

I've also tried adding it after markdown highlighted log (###==**Log**) and it works.

It didn't work with #### <mark style="background: #ABF7F7A6;">Log</mark>, so I've moved away from that.
