### ISSUE TITLE
Examples of using quickAdd to pull events from current day google calendar?

### ISSUE THREAD

**Issue by tonyxiao** [chhoumann/quickadd#300]
Has anyone been able to use QuickAdd to pull events from current day's google calendar?

**Comment by errbufferoverfl** [comment]
Using the [Google Calendar Plugin](https://github.com/YukiGasai/obsidian-google-calendar) I made [a small proof of concept script](https://gist.github.com/errbufferoverfl/c1016c5f112778c4bcb86c040ea339a5) to import events from Google Calendar.

Using a bit of hackery I was also able to extend it so that given a daily note, you could import all the events you had RSVPed yes to from Google Calendar -- happy to share that if that's what you're looking for.

**Comment by chhoumann** [comment]
This is fantastic. Thank you for sharing, @errbufferoverfl.

If you ever find the time, I'd love to see a PR adding it to the [QuickAdd docs](https://quickadd.obsidian.guide/docs/).
I think a lot of people would benefit from it.

Thank you!
