### ISSUE TITLE
Broken links to documentation

### ISSUE THREAD

**Issue by tophee** [chhoumann/quickadd#426]
Just a very minor thing: is the double `docs` in the path intentional?

![Arc-2023-03-20 at 10 38 29@2x](https://user-images.githubusercontent.com/3662750/226301671-6883bf0a-d7ef-4a2a-84f8-4cce6d058963.png)

It wasn't there some months ago and the change breaks existing links to the docs...

**Comment by chhoumann** [comment]
Hey @tophee!

Yes, it is intentional. It came after a recent revamp of the documentation.

Are there any broken links I could fix or should be aware of? Hopefully I caught all of them when I did the revamp, but can have missed some.

**Comment by chhoumann** [comment]
I chose to use another documentation service, as the previous one was causing headaches for me.
If I were to revert the changes, all newer links would break, which isn't desirable either.
Breaking changes suck to make. You know you're disrupting the service for a bunch of people, but sometimes have to do it in order to upgrade the product.

I apologize for any inconvenience this may have caused. I'll happily redirect anyone that cannot find their way to a piece of documentation.
