### ISSUE TITLE
[BUG] Templater syntax does not work in capture

### ISSUE THREAD

**Issue by HEmile** [chhoumann/quickadd#51]
I have a capture with a Templater template (ie, it has `<% tp.file.include() %>` in it. These do not resolve when I use it in a capture. I would like to do this because I want to run a macro after inserting the template. 

**Expected behavior**
I would have expected the templater includes to resolve. 

**Screenshots**
Capture setup
![image](https://user-images.githubusercontent.com/1289165/125946214-1eda4148-34ae-4000-b34b-58e524663cf3.png)

Result of capture
![image](https://user-images.githubusercontent.com/1289165/125946173-1f5d52ac-8072-4ef9-99e7-29e63c2f69be.png)

**Desktop (please complete the following information):**
 - OS: MacOSX

**Comment by chhoumann** [comment]
Hey! Thank you very much for your report. The issue should be fixed in v0.3.10. 

Would you please report back if it works for you now? =D

**Comment by HEmile** [comment]
Hi Christian! Thank you, yes it worked! But it looks like there is one more bug: It is not waiting long enough I think for Templater to resolve, meaning that the location property added using MetaEdit will create its own 'frontmatter':

![image](https://user-images.githubusercontent.com/1289165/126038011-9849dc13-75e1-4d51-a25f-57eae2f780ab.png)

**Comment by chhoumann** [comment]
Sorry for the delay in answering!

I've been doing some testing, and this does not seem to be a _bug_ per se.

The problem seems to be a combination of smaller parts that aren't exactly compatible. Let me explain.

When QuickAdd receives the format syntax, it'll evaluate and parse _all of it_ before inserting it into the page. So, in your example, both the template and macro will be executed before they're inserted.

However, MetaEdit's `createYamlProperty` does not play well with that - it reads the file as soon as it is executed. But there isn't any content on the page yet, so it'll create a new YAML field.
And _then_ the template is written to the page.

Luckily, we can solve this problem!

First, you should remove the macro from the format syntax in your `Add Location from Title` capture. So we avoid an infinite recursive loop.

Instead, we'll create a new macro. This macro should first run the capture choice, save the file, wait for a small delay, and then run the script that adds the location.

Here's a short GIF to demonstrate what I mean.
I use different names from your in the GIF, but basically:
`Test3` is your capture, and `test_script` is the script to add the current location to the file with MetaEdit.

![YGR2MedtWS](https://user-images.githubusercontent.com/29108628/126209808-efc6fcc4-3303-49f5-bdf9-0c547c0c7403.gif)

It's important that we save the file and wait a slight delay, so Obsidian actually saves the file before executing the macro.

Hope this helps!

**Comment by HEmile** [comment]
Ohhhhh! I get it now! That's super powerful, haha. So macro is where I need to be to 'script', very cool. This works super well, thank you so much! Will definitely be using QuickAdd more for stuff I need to automate ^^
