### ISSUE TITLE
[BUG] Failed to load user script /scripts/AutomaticBookNotesFromReadwise.js. Default export is not a function.

### ISSUE THREAD

**Issue by leonardsellem** [chhoumann/quickadd#54]
**Describe the bug**
When I launch the add book notes macro, an error message displays : "Failed to load user script /scripts/AutomaticBookNotesFromReadwise.js. Default export is not a function.".
Anyway, it creates a file for my book, but with a degraded template.

**To Reproduce**
1. Go to 'command palette'
2. Click on 'run QuickAdd'
3. Click on 'Add book'
4. Click on a book name

**Expected behavior**
A file should be created on the model of my template, with every variable filled properly.

**Screenshots**
[![Capture-d-e-cran-2021-07-21-a-11-06-17.png](https://i.postimg.cc/X7Dn0mJk/Capture-d-e-cran-2021-07-21-a-11-06-17.png)](https://postimg.cc/WhrBG90d)

**Desktop (please complete the following information):**
 - OS: MacOS 11.4
 - Browser Brave V1.26.77 (July 16, 2021)
 - Obsidian Version 0.12.10

**Comment by chhoumann** [comment]
Hey, @leonardsellem! Thank you for your report.

It looks like it's Templater that's complaining. Templater doesn't support that type of script, which is why I have the `{{MACRO:Readwise::instaFetchBook}}` in my book notes template. 

Although, it does seem like the script ran (drawing this from the Author field being filled out), so I'm wondering if you both activate the script _and_ try to call it from Templater?

**Comment by leonardsellem** [comment]
Hi @chhoumann , thank you for your quick feedback !
Do you mean I need to deactivate Templater ?

**Comment by chhoumann** [comment]
That shouldn't be needed. But could you show me your entire template?

**Comment by leonardsellem** [comment]
---
image: 
tags: in/books
aliases:
  - <% tp.file.title.replace('{ ', '') %>
cssclass: 
---

# Title: [[<%tp.file.title%>]]

## Metadata

Tags:: 
Type:: [[{]]
Author:: {{VALUE:author}}
Reference::
Rating:: 
Reviewed Date:: [[<%tp.date.now("gggg-MM-DD - ddd MMM D")%>]]
Finished Year:: [[<%tp.date.now("gggg")%>]]

# Thoughts

# Actions Taken / Changes

# Summary of Key Points

# Highlights & Notes
{{MACRO:Readwise::instaFetchBook}}

**Comment by leonardsellem** [comment]
`---
image: 
tags: in/books
aliases:
  - <% tp.file.title.replace('{ ', '') %>
cssclass: 
---

# Title: [[<%tp.file.title%>]]

## Metadata

Tags:: 
Type:: [[{]]
Author:: {{VALUE:author}}
Reference::
Rating:: 
Reviewed Date:: [[<%tp.date.now("gggg-MM-DD - ddd MMM D")%>]]
Finished Year:: [[<%tp.date.now("gggg")%>]]

# Thoughts

# Actions Taken / Changes

# Summary of Key Points

# Highlights & Notes
{{MACRO:Readwise::instaFetchBook}}`

**Comment by leonardsellem** [comment]
```
---
image: 
tags: in/books
aliases:
  - <% tp.file.title.replace('{ ', '') %>
cssclass: 
---

# Title: [[<%tp.file.title%>]]

## Metadata

Tags:: 
Type:: [[{]]
Author:: {{VALUE:author}}
Reference::
Rating:: 
Reviewed Date:: [[<%tp.date.now("gggg-MM-DD - ddd MMM D")%>]]
Finished Year:: [[<%tp.date.now("gggg")%>]]

# Thoughts

# Actions Taken / Changes

# Summary of Key Points

# Highlights & Notes
{{MACRO:Readwise::instaFetchBook}}
```

**Comment by leonardsellem** [comment]
Highlights are being imported through

**Comment by chhoumann** [comment]
Thank you! Do you by chance have your Templater scripts folder set to the same folder as the one you placed this script in?

I'm referring to this setting in Templater
![image](https://user-images.githubusercontent.com/29108628/126490451-251427c5-c166-4cd2-88b8-94049d98e2c8.png)

Because if you did, Templater will try to 'understand' it - which it can't, because it's not supported by Templater.

As you can see in my image, I actually ended up giving Templater its own folder within my 'scripts' folder.

So maybe just create a separate folder for QuickAdd scripts. Or do what I did and create a 'Templater' folder within your scripts folder and tell Templater to look there - and move your Templater scripts there, of course.

**Comment by leonardsellem** [comment]
You rock ! It works so well !
