### ISSUE TITLE
Error while loading the plugin.

### ISSUE THREAD

**Issue by munish259272** [chhoumann/quickadd#728]
**Describe the bug**
I am not facing any issue but in the developer console it shows like this below the loading information for quick add.

is this something to be concerned about or can be ignored.

`Uncaught (in promise) DOMException: Failed to execute 'structuredClone' on 'Window': W=>b(d=>({...d,...W})) could not be cloned.
    at structuredCloneInternal (app://obsidian.md/lib/pdfjs/pdf.min.js:22:149521)
    at structuredCloneInternal (app://obsidian.md/lib/pdfjs/pdf.min.js:22:150684)
    at structuredClone (app://obsidian.md/lib/pdfjs/pdf.min.js:22:153395)
    at i5 (plugin:quickadd:55:5868)
    at async GI.onload (plugin:quickadd:73:7765)`

**Comment by chhoumann** [comment]
QuickAdd tries to back up settings while it updates after new releases. This uses the structuredClone function you see. However, it seems some other plugin or functionality is interfering by overwriting it. If you have any PDF tools, or maybe it's Obsidians own, they are trying to import a library called "pdf.js". This is the tool that is creating the error. 

Basically, this means there may be errors when the plugin updates its settings when a new version is out. It's not due to QuickAdd, but some other plugin using pdf.js.

**Comment by baodrate** [comment]
fwiw, I can reproduce this error with an empty vault, no community plugins other than quickadd, and all core plugins disabled (Obsidian v1.7.1)

**Comment by mochsner** [comment]
Was very much looking forward to trying this plug-in after watching some videos, but running into the same issue. Was hopeful to find this, but are there any workarounds? For me it occurs when I try to toggle QuickAdd as enabled, not when running an action.

![image](https://github.com/user-attachments/assets/d5dfd4c8-01d4-4d84-b788-860860a6f1c3)
QuickAdd: 1.11.1
Obsidian: 1.7.4
OS: Ubuntu 20.04

**Comment by baodrate** [comment]
workaround detailed here: https://github.com/chhoumann/quickadd/issues/746#issuecomment-2437651398

**Comment by chhoumann** [comment]
Hey, I'm sorry for taking so long about getting this fixed! It should hopefully be resolved now. I hope you enjoy QuickAdd, and please let me know if there are any further issues. All the best, Christian.

**Comment by mochsner** [comment]
Confirmed all fixed... and yes, definitely enjoying it, thank you for your hard work @chhoumann !
