### ISSUE TITLE
[FEATURE REQUEST] Enable "Insert capture after specified line" when "Capture to active file" is on

### ISSUE THREAD

**Issue by mrpurplecloud** [chhoumann/quickadd#73]
**Is your feature request related to a problem? Please describe.**

I think the "Insert capture after specified line" option in Capture choice is very cool and use it a lot, unfortunately it is not possible when I turn on the "Capture to active file" switch.

**Describe the solution you'd like**

Please don't treat "Capture to active file" as a special case and enable all the Capture choice features when capturing to active file, as the active file sometimes already exists. Inserting capture to specific position in active file would be very useful in cases like updating current note's YAML properties etc. Thanks!

**Comment by Xtremefaith** [comment]
I know this is marked as an enhancement, but feels like a defect because the ability is clearly available and then it just goes missing when writing to the active file. I'm trying to do more than just daily notes with this and it's a pretty big limitation especially considering what I've now down with it in my daily notes template.

**Comment by the0s0ph1st** [comment]
I read in one post that if enough attention is given to a problem then it might get fixed earlier. So I'm bumping this with an appeal to fix this and a request: is there workaround better than what I have been doing to do this? 

I am not a programmer so my approach is heavily dependent on other apps. So far I have been using QuickAdd to replicate this by first typing the text on the note then, using Quickadd to

(1) highlight the text
(2) cut it
(3) use regex find and replace using Apply Patterns to add "<% tp.file.cursor(1) %>" below the line I want to move the text to
(4) run Templater to move the cursor there
(5) paste the text.

For some reason "tp.system.clipboard()" does not work on at least Android mobile which is why use this workaround. Problem is, the macro sometimes does not work when I don't reload Obsidian, so I am looking better ways of doing it.

**Comment by chhoumann** [comment]
Adding this soon. Already started working on it earlier today, along with other improvements to the capture workflow. 

And you're right, @the0s0ph1st. Bumping / liking feature requests help me prioritize them. 
That's why I'm working on this one + other capture requests.

**Comment by the0s0ph1st** [comment]
Oof I hope this is going to be in the next app update! So bumping this and also bribed you with coffee lol.

Seriously though thanks for doing what is essentially free stuff for us. The latest capture changes are great!

**Comment by chhoumann** [comment]
@the0s0ph1st The coffee helped fuel a coding session to get this added. Thank you 💙!
Glad you like the latest changes.

**Comment by chhoumann** [comment]
Ok everyone, I've just added this in v0.18.x!

Everything but 'create fix if it doesn't exist' and 'open file' is available when capture to active file is enabled:
![image](https://user-images.githubusercontent.com/29108628/229476987-86b40f07-d6b1-4049-af0d-31ea2e6d9666.png)

Please let me know if this works as expected. :)
I've done some testing myself, and seems to be quite functional.
